In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
base_risco_credito = pd.read_csv('../data/risco_credito.csv');

In [3]:
base_risco_credito.describe()

historia divida garantias     renda risco
count             14     14        14        14    14
unique             3      2         2         3     3
top     desconhecida   alta   nenhuma  acima_35  alto
freq               5      7        11         7     6

In [4]:
base_risco_credito.head()

historia divida garantias     renda     risco
0          ruim   alta   nenhuma      0_15      alto
1  desconhecida   alta   nenhuma     15_35      alto
2  desconhecida  baixa   nenhuma     15_35  moderado
3  desconhecida  baixa   nenhuma  acima_35      alto
4  desconhecida  baixa   nenhuma  acima_35     baixo

In [5]:
base_risco_credito.tail()

historia divida garantias     renda     risco
9       boa   alta  adequada  acima_35     baixo
10      boa   alta   nenhuma      0_15      alto
11      boa   alta   nenhuma     15_35  moderado
12      boa   alta   nenhuma  acima_35     baixo
13     ruim   alta   nenhuma     15_35      alto

In [6]:
x_risco_credito = base_risco_credito.iloc[:, 0:4].values
x_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [7]:
y_risco_credito = base_risco_credito.iloc[:, 4].values
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

print(x_risco_credito)

for i in [0, 1, 2, 3]:
    x_risco_credito[:, i] = label_encoder.fit_transform(x_risco_credito[:, i]);

print(x_risco_credito)

[['ruim' 'alta' 'nenhuma' '0_15']
 ['desconhecida' 'alta' 'nenhuma' '15_35']
 ['desconhecida' 'baixa' 'nenhuma' '15_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'nenhuma' 'acima_35']
 ['desconhecida' 'baixa' 'adequada' 'acima_35']
 ['ruim' 'baixa' 'nenhuma' '0_15']
 ['ruim' 'baixa' 'adequada' 'acima_35']
 ['boa' 'baixa' 'nenhuma' 'acima_35']
 ['boa' 'alta' 'adequada' 'acima_35']
 ['boa' 'alta' 'nenhuma' '0_15']
 ['boa' 'alta' 'nenhuma' '15_35']
 ['boa' 'alta' 'nenhuma' 'acima_35']
 ['ruim' 'alta' 'nenhuma' '15_35']]
[[2 0 1 0]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 1 1 2]
 [1 1 0 2]
 [2 1 1 0]
 [2 1 0 2]
 [0 1 1 2]
 [0 0 0 2]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 1 2]
 [2 0 1 1]]


# Training algorithm

In [9]:
from sklearn.naive_bayes import GaussianNB

naive_risco_credito = GaussianNB()
naive_risco_credito.fit(x_risco_credito, y_risco_credito)

GaussianNB()

In [15]:
# historia boa (0), divida alta (0), garantias nenhuma (1), renda > 35 (2)
naive_risco_credito.predict([[0, 0, 1, 2]])

array(['baixo'], dtype='<U8')